### PR TITLE
fix(ui): constrain wallet name to 30 chars max

### LINKED ISSUE #1529: Better handling for extremely long wallet names
add a character limit to the wallet names so as if to minimize UI/UX disruptions

## Possible Fix

introduce a character limit to the wallet name

## Steps to Reproduce

use an extremely long wallet name 

- Zap Desktop version: 0.3.4-beta
- Operating System and version: mac osX

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

 - maxLength and minLength input validators
 - constrain wallet name to 30 chars max

## Motivation and Context:

Fix #1529

## How Has This Been Tested?

Manually

## Types of changes:

Enhancement

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [ x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: renderer/hocs/withInputValidation.js [hunk 1]
```diff
@@ -23,15 +25,22 @@ const withRequiredValidation = Component =>
...
-          const validator = yup.string().required()
-          validator.validateSync(value)
+          validator = validator.required()
         }
+        if (minLength) {
+          validator = validator.min(minLength)
+        }
+        if (maxLength) {
+          validator = validator.max(maxLength)
+        }
```
Comment (korhaliv) [inline renderer/hocs/withInputValidation.js]: Will this validate correctly BOTH `maxLength` and `minLength` at a time?

Comment (mrfelton) [reply renderer/hocs/withInputValidation.js]: It should do - each conditional adds an additional check to the validator
