### PR TITLE
 fix(ui): center WalletCreate content

### LINKED ISSUE #2918: "Creating wallet" processing message should be vertically centred on the page
## Description

"Creating Wallet" processing message should be  vertically centred on the page 

image

## Expected Behavior

Message and spinner should be centred

## Actual Behavior

Message and spinner show right at the top of the page, leaving a large empty space and making the page look a little unfinished

## Steps to Reproduce

Create a new internal wallet

## Context

Onboarding

### PR DESCRIPTION
**Pull request by korhaliv**
## Description:
Resolves #2918 

## How Has This Been Tested?
Manually

## Screenshot
image

## Types of changes:
Bugfix

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [ ] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: renderer/components/Onboarding/Steps/WalletCreate.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ import React from 'react'
 import PropTypes from 'prop-types'
 import { FormattedMessage } from 'react-intl'
 import { Spinner, Text } from 'components/UI'
+import CenteredContent from 'components/UI/CenteredContent'
```
Comment (mrfelton) [inline renderer/components/Onboarding/Steps/WalletCreate.js]: This should probably be combined into the above named imports from `components/UI`
