### PR TITLE
fix(onboarding): improve handling of empty form values

### LINKED ISSUE #2146: Error when trying to save a wallet without a name or alias
## Description

Getting an error when trying to save a wallet without a name or alias.

image

## Expected Behavior

Should save without error

## Steps to Reproduce

Try to save a wallet without a name and/or alias.

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

- improve handling of empty form values
- strip unknown properties in db.wallet

## Motivation and Context:

Fix #2146 

Additionally, be more strict about which wallet properties we save into the db. Do not save things that are supposed to be dynamically generated at runtime. Instead, generate them after fetching the wallets from the database. This ensures that if we change our underlaying setup at a later date users do not end up with stale wallet configs in their database.

**before:**

image

**after:**

image

## How Has This Been Tested?

Manually

## Types of changes:

Bug fix / enhancement

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [ ] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: electron/preload.js [hunk 1]
```diff
@@ -94,7 +94,7 @@ async function generateLndConfigFromWallet(wallet) {
   // Wait for the config to become fully initialized.
   await lndConfig.isReady
 
-  return lndConfig
+  return Object.assign({}, lndConfig)
```
Comment (korhaliv) [inline electron/preload.js]: Could you add a comment here, please? I assume we just create an independent copy of config here, so the original one stays untouched no matter what?

Comment (mrfelton) [reply electron/preload.js]: Have added some comments to this.
