### PR TITLE
 fix: retry paying invoice after failure

### LINKED ISSUE #1884: Can't find route initially, going back > send works
## Description
When I'm pasting an invoice, it usually can't find a route and won't show me estimated fees (and the payment would fail)....at this point, I click back to see the invoice again, and then next - now it shows estimated fees and the payment goes through. Is this something just with lnd, or happening client side? Should it try to broadcast the message multiple times?

## Steps to Reproduce

- 1.
- 2.
- 3.
- 4.

## Your Environment

- Zap version:
- Operating System and version:

### PR DESCRIPTION
**Pull request by korhaliv**
## Description:
Fix #1884

## Motivation and Context:
To address route failures this PR introduces 2 enhancements:
1. Query routes each time the user goes from invoice to summary page in Pay form
2. Add retries for failed payments

## How Has This Been Tested?
Manually

## Types of changes:
Enhancement/bugfix

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [ ] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: renderer/components/Pay/Pay.js [hunk 1]
```diff
@@ -346,10 +345,19 @@ class Pay extends React.Component {
...
-    const { currentStep } = this.state
-    const nextStep = Math.min(this.steps().indexOf(currentStep) + 1, this.steps().length - 1)
-    if (currentStep !== nextStep) {
-      this.setState({ currentStep: this.steps()[nextStep], previousStep: currentStep })
+    const { currentStep, invoice } = this.state
+    const nextStepIndex = Math.min(this.steps().indexOf(currentStep) + 1, this.steps().length - 1)
+    const nextStep = this.steps()[nextStepIndex]
+
+    // update route
+    if (invoice && nextStep === 'summary') {
```
Comment (mrfelton) [inline renderer/components/Pay/Pay.js]: I feel like this would be better handled in `componentDidUpdate` as it muddies the scope of the `nextStep` method a little.

File: renderer/reducers/payment.js [hunk 2]
```diff
@@ -16,6 +16,7 @@ export const RECEIVE_PAYMENTS = 'RECEIVE_PAYMENTS'
 export const SEND_PAYMENT = 'SEND_PAYMENT'
 export const PAYMENT_SUCCESSFUL = 'PAYMENT_SUCCESSFUL'
 export const PAYMENT_FAILED = 'PAYMENT_FAILED'
+export const DEC_PAYMENT_RETRIES = 'DEC_PAYMENT_RETRIES'
```
Comment (mrfelton) [inline renderer/reducers/payment.js]: Lets rename to `DECREMENT_PAYMENT_RETRIES` for clarity (same for other instances of `dec`)
