### PR TITLE
fix(wallet): present correct fee when no route

### LINKED ISSUE #3154: Fee rate displayed as less than 1 satoshi when route and fee is actually unknown
## Description

Fee rate displayed as 1 satoshi when route and fee is actually unknown.

## Expected Behavior

If no routes are found when running query routes we should dispkay the fee as `unknown`

## Actual Behavior

We display the fee as `less than 1 satoshi`

## Steps to Reproduce

Try to pay an invoice where a route can not be found (eg, create an invoice and try to pay your own invoice).

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

Ensure fee rate is displayed as `unknown` if no routes are found.

## Motivation and Context:

Fix #3154

## How Has This Been Tested?

Manually

## Types of changes:

Bug fix

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: renderer/components/Pay/PaySummaryLightning.js [hunk 1]
```diff
@@ -76,7 +76,7 @@ class PaySummaryLightning extends React.Component {
     let feeMessage = messages.fee_unknown
 
     // If thex max fee is 0 or 1 then show a message like "less than 1".
-    if (maxFee === 0 || maxFee === 1) {
+    if (maxFee >= 0 && maxFee <= 1) {
```
Comment (korhaliv) [inline renderer/components/Pay/PaySummaryLightning.js]: message says less than 1 while we use `<=1` ?

File: renderer/reducers/pay.js [hunk 2]
```diff
@@ -225,7 +225,7 @@ export const queryRoutes = (pubKey, amount) => async dispatch => {
     })
     dispatch({ type: QUERY_ROUTES_SUCCESS, routes })
   } catch (e) {
-    dispatch({ type: QUERY_ROUTES_FAILURE })
+    dispatch({ type: QUERY_ROUTES_FAILURE, error: e.message })
```
Comment (korhaliv) [inline renderer/reducers/pay.js]: Not something that the PR has touched but in 
queryFees error serialization is a bit different.
`const error = get(e, 'response.statusText', e)`
Should probably change to
```
    const error = get(e, 'response.statusText', e.message)
```
there
