### PR TITLE
fix(ui): improve channel list search and filter

### LINKED ISSUE #847: Pending channel connection.
Channel never connects, funding transaction never completes.

## Steps to Reproduce

- 1. Create new wallet
- 2. Fund wallet
- 3. Try and connect to Yalls with funding transaction
- 4. Transaction to open channel and connect always pending...

## Context

Unable to use the very basics of the app

## Your Environment

- Zap Desktop version: 0.2.2
- Operating System and version: Mac OS High Sierra 10.13.6

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

Refactor the channels reducer so that we reuse selectors as much as possible, and augment channels with additional metadata used for display purposes.

## Motivation and Context:

Fix #1244
Fix #847

## How Has This Been Tested?

Manually - give the network pane a good run for its money.

## Types of changes:

Bug fixes.

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: app/components/Contacts/Network/Network.js [hunk 1]
```diff
@@ -289,13 +244,11 @@ class Network extends Component {
...
-                          data-hint={intl.formatMessage({ ...messages[status] })}
+                          data-hint={intl.formatMessage({ ...messages[display_status] })}
                         >
-                          <StatusIndicator variant={status} />
+                          <StatusIndicator variant={display_status} />
                         </Box>
-                        <Text css={{ '&:hover': { opacity: 0.5 } }}>
-                          {displayNodeName(channel)}
-                        </Text>
+                        <Text css={{ '&:hover': { opacity: 0.5 } }}>{display_name}</Text>
```
Comment (korhaliv) [inline app/components/Contacts/Network/Network.js]: Would be nice to use styled here

File: app/components/Contacts/Network/Network.js [hunk 2]
```diff
@@ -306,7 +259,7 @@ class Network extends Component {
                             onClick={() =>
                               blockExplorer.showTransaction(
                                 networkInfo,
-                                channelObj.closing_txid || channel.channel_point.split(':')[0]
+                                closing_txid || channel_point.split(':')[0]
```
Comment (korhaliv) [inline app/components/Contacts/Network/Network.js]: I suppose `channel_point` can't be null? I see it's also used as a key

File: app/reducers/channels.js [hunk 3]
```diff
@@ -44,19 +43,113 @@ export const RECEIVE_SUGGESTED_NODES_ERROR = 'RECEIVE_SUGGESTED_NODES_ERROR'
...
+ */
+const getDisplayName = (channel, nodes) => {
+  const remoteNodePubkey = getRemoteNodePubKey(channel)
+  const node = nodes.find(n => n.pub_key === remoteNodePubkey)
+
+  if (node && node.alias && node.alias.length) {
+    return node.alias
+  }
+
+  return remoteNodePubkey.substring(0, 10)
```
Comment (korhaliv) [inline app/reducers/channels.js]: An util for this is in `next` I suppose ?

File: app/components/Contacts/Network/Network.js [hunk 4]
```diff
@@ -263,17 +212,23 @@ class Network extends Component {
...
               {currentChannels.length > 0 &&
-                currentChannels.map((channelObj, index) => {
-                  const channel = Object.prototype.hasOwnProperty.call(channelObj, 'channel')
-                    ? channelObj.channel
-                    : channelObj
-                  const pubkey = channel.remote_node_pub || channel.remote_pubkey
-                  const isSelected = selectedChannel === channel
-                  const status = channelStatus(channelObj)
+                currentChannels.map(channelObj => {
+                  const channel = channelObj.channel || channelObj
```
Comment (korhaliv) [inline app/components/Contacts/Network/Network.js]: Could you please add this comment here
// If this is a pending channel, the channel data will be stored under the `channel` key.

File: app/reducers/channels.js [hunk 5]
```diff
@@ -44,19 +43,113 @@ export const RECEIVE_SUGGESTED_NODES_ERROR = 'RECEIVE_SUGGESTED_NODES_ERROR'
...
+ * @param  {Object} channelObj Channel object.
+ * @param  {Array} nodes Array of node data.
+ * @param  {Array} closingChannelIds List of channel ids that we are in the process of closing.
+ * @return {Object} Decorated channel object.
+ */
+const decorateChannel = (channelObj, nodes, closingChannelIds) => {
+  // If this is a pending channel, the channel data will be stored under the `channel` key.
+  const channelData = channelObj.channel || channelObj
+
+  const display_pubkey = getRemoteNodePubKey(channelData)
```
Comment (korhaliv) [inline app/reducers/channels.js]: Can we use camelCase here please? And then name them accordingly in `updatedChannelData`

File: app/reducers/channels.js [hunk 6]
```diff
@@ -411,158 +494,139 @@ const ACTION_HANDLERS = {
...
 const nodesSelector = state => state.network.nodes
 
-const channelMatchesQuery = (channel, nodes, searchQuery) => {
-  const node = nodes.find(n => channel.remote_pubkey === n.pub_key)
+const channelMatchesQuery = (channelObj, searchQuery) => {
+  if (!searchQuery) {
+    return true
+  }
+
+  const channel = channelObj.channel || channelObj
```
Comment (korhaliv) [inline app/reducers/channels.js]: I see this pattern a lot. Maybe it's a good idea to get a helper function like `getChannelObject()`

File: app/components/Contacts/Network/Network.js (hunk 2 above)
Comment (mrfelton) [reply app/components/Contacts/Network/Network.js]: Yes - following on from our discussion the other day about trying to identify a unique key for the channels, I found that whilst `chan_id` is not always set, `channel_point` and I believe it to be unique. From the docs:


```
The outpoint (txid:index) of the funding transaction. With this value, Bob will be able to generate a signature for Alice’s version of the commitment transaction.
```

```
funding_txid_bytes | bytes | Txid of the funding transaction
funding_txid_str | string | Hex-encoded string representing the funding transaction
output_index | uint32 | The index of the output of the funding transaction
````
https://api.lightning.community/#channelpoint

This identifier is used to uniquely identify channels for several operations in the lnd api.

File: app/reducers/channels.js (hunk 3 above)
Comment (mrfelton) [reply app/reducers/channels.js]: Well, `getDisplayName` is the utility function which in the next branch I have used to replace the multiple instances where we are calling `.substring(0, 10)` on the channel pubkey.

So this will be the one remaining instance of this call.

File: app/components/Contacts/Network/Network.js (hunk 1 above)
Comment (mrfelton) [reply app/components/Contacts/Network/Network.js]: I want to try to limit the scope of this PR to resolving some of the search/filter related issues and don't want to get into refactoring out into separate components here. We have already done that in the `next` branch.

File: app/reducers/channels.js (hunk 5 above)
Comment (mrfelton) [reply app/reducers/channels.js]: Updated

File: app/reducers/channels.js (hunk 6 above)
Comment (mrfelton) [reply app/reducers/channels.js]: Updated

**Comment by mrfelton** [comment]
I've updated some of these items @korhaliv and left some comments on others that I didn't feel right to address here.
