### PR TITLE
fix(ui): ensure fiat and crypto inputs in agroup are always updated

### LINKED ISSUE #2602: USD amount not populated on send all
When toggling the `Send all of your funds` toggle in the pay form, the USD amount is not populated:

Screen Shot 2019-07-23 at 10 22 34 AM

### PR DESCRIPTION
**Pull request by korhaliv**
## Description:
fix  #2602

## How Has This Been Tested?
Manually

## Types of changes:
Bugfix

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [ ] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: renderer/components/UI/CurrencyFieldGroup.js [hunk 1]
```diff
@@ -88,7 +99,7 @@ const CurrencyFieldGroup = React.forwardRef(
                 isRequired={isRequired}
                 label={cryptoLabel || <FormattedMessage {...messages.amount} />}
                 name="amountCrypto"
-                onChange={handleAmountCryptoChange}
+                onValueChange={handleAmountCryptoChange}
```
Comment (mrfelton) [inline renderer/components/UI/CurrencyFieldGroup.js]: It's no longer possible to enter a number into the crypto amount field on the pay form. I have a feeling it may be related to this change. I think it causes some kind conflict with other onchange handlers that kick in as part of the number field handling.

File: renderer/components/UI/CurrencyFieldGroup.js [hunk 2]
```diff
@@ -34,26 +34,37 @@ const CurrencyFieldGroup = React.forwardRef(
...
+      }
     }
 
     /**
      * handleAmountFiatChange - Set the amountCrypto field whenever the fiat amount changes.
      *
      * @param {Event} e Event
      */
-    const handleAmountFiatChange = e => {
+    const handleAmountFiatChange = async value => {
```
Comment (mrfelton) [inline renderer/components/UI/CurrencyFieldGroup.js]: Async not needed here.

**Comment by korhaliv** [comment]
@mrfelton are you sure you don't have "send all" enabled? In that case fields are not editable (same behavior before this PR)
Nevertheless, this issue is really tricky. I've identified some more corner cases where a circular update was happening as well as fees were not updating when pressing enabling send all (same in current next).  I've re-done impl from scratch, so re-view is required.

**Comment by mrfelton** [comment]
I didn’t have send all enabled. I could type in the fiat box, but not the crypto one

**Comment by korhaliv** [comment]
> I didn’t have send all enabled. I could type in the fiat box, but not the crypto one

ok, please try updated version then and let me know if the issue persists

File: renderer/components/UI/CurrencyFieldGroup.js [hunk 3]
```diff
@@ -30,30 +30,57 @@ const CurrencyFieldGroup = React.forwardRef(
...
   ) => {
+    // whether update of a linked input (crypto<->fiat) is enabled
+    // this ref is used in a process of linked value calculations to
+    // circular updates
+    const shouldUpdateLinked = useRef(true)
+
     /**
      * handleAmountCryptoChange - Set the amountFiat field whenever the crypto amount changes.
      *
      * @param {Event} e Event
```
Comment (mrfelton) [inline renderer/components/UI/CurrencyFieldGroup.js]: param doc needs updating (e -> value)

**Comment by mrfelton** [comment]
Updated version does work @korhaliv 

I'm wondering though wether we can reduce the duplication here a little. What do you think about something like this:

```js
    // Whether update of a linked input (crypto<->fiat) is enabled.
    // This ref is used in a process of linked value calculations to prevent circular updates.
    const blockUpdates = useRef(true)

    // Prevent updates of linked form values.
    const blockLinkedUpdates = () => {
      blockUpdates.current = false
    }

    // Reenable updates of linked form elements.
    const unblockLinkedUpdates = async () => {
      await Promise.resolve()
      blockUpdates.current = true
    }

    // Get current block status of linked form elements.
    const isLinkedUpdatesBlocked = () => {
      return blockUpdates.current
    }

    /**
     * handleAmountCryptoChange - Set the amountFiat field whenever the crypto amount changes.
     *
     * @param {Event} value Value
     */
    const handleAmountCryptoChange = async value => {
      const lastPrice = currentTicker[fiatCurrency]
      const fiatValue = convert(cryptoUnit, 'fiat', value, lastPrice)
      if (!isLinkedUpdatesBlocked()) {
        blockLinkedUpdates()
        formApi.setValue('amountFiat', fiatValue)
      }
      unblockLinkedUpdates()
      onChange && onChange()
    }

    /**
     * handleAmountFiatChange - Set the amountCrypto field whenever the fiat amount changes.
     *
     * @param {Event} value Value
     */
    const handleAmountFiatChange = async value => {
      const lastPrice = currentTicker[fiatCurrency]
      const cryptoValue = convert('fiat', cryptoUnit, value, lastPrice)
      if (!isLinkedUpdatesBlocked()) {
        blockLinkedUpdates()
        formApi.setValue('amountCrypto', cryptoValue)
      }
      unblockLinkedUpdates()
      onChange && onChange()
    }
```

It's essentially the same code that you had but with the special logic extracted to some helper methods. I feel like this makes the change handlers themselves a little easier to read and with less duplication.

File: renderer/components/UI/CurrencyFieldGroup.js [hunk 4]
```diff
@@ -30,30 +30,66 @@ const CurrencyFieldGroup = React.forwardRef(
...
-      const lastPrice = currentTicker[fiatCurrency]
-      const value = convert(cryptoUnit, 'fiat', e.target.value, lastPrice)
-      formApi.setValue('amountFiat', value)
+    const handleAmountCryptoChange = async value => {
+      if (!isLinkedUpdatesBlocked()) {
+        const lastPrice = currentTicker[fiatCurrency]
+        const fiatValue = convert(cryptoUnit, 'fiat', value, lastPrice)
+        blockLinkedUpdates()
+        formApi.setValue('amountFiat', fiatValue)
+        // informed calls onValueChange multiple time during value updates
```
Comment (mrfelton) [inline renderer/components/UI/CurrencyFieldGroup.js]: Can we move this comment into the `unblockLinkedUpdates` method?

File: renderer/components/UI/CurrencyFieldGroup.js [hunk 5]
```diff
@@ -30,30 +30,66 @@ const CurrencyFieldGroup = React.forwardRef(
...
-      const lastPrice = currentTicker[fiatCurrency]
-      const value = convert('fiat', cryptoUnit, e.target.value, lastPrice)
-      formApi.setValue('amountCrypto', value)
+    const handleAmountFiatChange = async value => {
+      if (!isLinkedUpdatesBlocked()) {
+        const lastPrice = currentTicker[fiatCurrency]
+        const cryptoValue = convert('fiat', cryptoUnit, value, lastPrice)
+        blockLinkedUpdates()
+        formApi.setValue('amountCrypto', cryptoValue)
+        // informed calls onValueChange multiple time during value updates
```
Comment (mrfelton) [inline renderer/components/UI/CurrencyFieldGroup.js]: and then remove from here too

File: renderer/components/UI/CurrencyFieldGroup.js [hunk 6]
```diff
@@ -30,30 +30,66 @@ const CurrencyFieldGroup = React.forwardRef(
...
      */
-    const handleAmountCryptoChange = e => {
-      const lastPrice = currentTicker[fiatCurrency]
-      const value = convert(cryptoUnit, 'fiat', e.target.value, lastPrice)
-      formApi.setValue('amountFiat', value)
+    const handleAmountCryptoChange = async value => {
+      if (!isLinkedUpdatesBlocked()) {
+        const lastPrice = currentTicker[fiatCurrency]
+        const fiatValue = convert(cryptoUnit, 'fiat', value, lastPrice)
+        blockLinkedUpdates()
```
Comment (mrfelton) [inline renderer/components/UI/CurrencyFieldGroup.js]: Could I suggest moving this line up to the top of this block so that it reads more like:

```
if (!isLinkedUpdatesBlocked()) {
  blockLinkedUpdates()
  // do stuff ...
  await unblockLinkedUpdates()
}
```

**Comment by korhaliv** [comment]
@mrfelton updated. i've also moved 
```
 onChange && onChange
``` 
out of `unblockLinkedUpdates`. Imo that code doesn't belong there semantically. Even though we have to call it twice now
