### PR TITLE
fix(ui): node and activity modals overhaul

### LINKED ISSUE #1614: Address modal bug (next branch)
In the next branch when clicking on the `qrcode` to access my address, URI and lndconnect QRCode I see the following UI:

screen shot 2019-02-20 at 6 50 44 pm

Also, clicking on `Node URI` makes the screen go blank

### PR DESCRIPTION
**Pull request by korhaliv**
## Description:
Bring node details and activity modals under the common modal system (modal stack)

## Motivation and Context:
Currently node and activity modals are standalone and thus are not benefiting from the existing modal system (transition animation, proper escape button handling etc), as well as causing rendering issues.

Modals are now part of the common stack and are also bound closer to a redux state source resulting in a minor perf improvements.

This PR also does some cleanup and refactoring of the top level `App` container

Fix #1614 

## How Has This Been Tested?
Manually

## Types of changes:
Bugfix and refactoring

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: app/components/Wallet/ReceiveModal/ReceiveModal.js [hunk 1]
```diff
@@ -123,61 +110,59 @@ class ReceiveModal extends React.PureComponent {
...
-            {qrCode && qrCodeType !== QRCODE_TYPE_LNDCONNECT && (
-              <QRCode value={qrCode} size="xlarge" />
-            )}
-            {qrCodeType === QRCODE_TYPE_LNDCONNECT && (
-              <>
-                <QRCode
-                  value={qrCode}
-                  size="xlarge"
-                  obfuscate={qrCodeType === QRCODE_TYPE_LNDCONNECT && !reveal}
+      <Box width={9 / 16} mx="auto">
```
Comment (mrfelton) [inline app/components/Wallet/ReceiveModal/ReceiveModal.js]: Rather than hard coding the width and margin onto this component, it would be better to apply `{...rest}` to the wrapping `Box`, and have these props passed in by the caller.

File: app/components/Activity/ActivityModal/ActivityModal.js [hunk 2]
```diff
@@ -42,11 +40,9 @@ export default class ActivityModal extends React.PureComponent {
     const SpecificModal = MODAL_COMPONENTS[item.type].component
 
     return (
-      <Modal onClose={hideActivityModal}>
-        <Box width={9 / 16} mx="auto">
-          <SpecificModal {...MODAL_COMPONENTS[item.type].props} />
-        </Box>
-      </Modal>
+      <Box width={9 / 16} mx="auto">
```
Comment (mrfelton) [inline app/components/Activity/ActivityModal/ActivityModal.js]: Same goes here. positioning props would be better passed in from the caller.

File: app/containers/ModalStack.js [hunk 3]
```diff
@@ -25,6 +27,12 @@ const ModalContent = ({ type, closeModal }) => {
     case 'REQUEST_FORM':
       return <Request width={9 / 16} mx="auto" />
 
+    case 'RECEIVE_MODAL':
+      return <ReceiveModal width={9 / 16} mx="auto" />
+
+    case 'ACTIVITY_MODAL':
+      return <ActivityModal width={9 / 16} mx="auto" />
```
Comment (mrfelton) [inline app/containers/ModalStack.js]: so the positioning props are already being passed in,. the just aren't being applied correctly.

File: app/components/Wallet/ReceiveModal/ReceiveModal.js (hunk 1 above)
Comment (korhaliv) [reply app/components/Wallet/ReceiveModal/ReceiveModal.js]: I didn't hardcode them (this is how it was), but your suggestion makes sense

Comment (korhaliv) [reply app/components/Wallet/ReceiveModal/ReceiveModal.js]: updated

File: app/components/Activity/ActivityModal/ActivityModal.js (hunk 2 above)
Comment (korhaliv) [reply app/components/Activity/ActivityModal/ActivityModal.js]: updated

File: app/containers/ModalStack.js (hunk 3 above)
Comment (korhaliv) [reply app/containers/ModalStack.js]: updated
