### PR TITLE
Fetch latest paymet on external htlc settle

### LINKED ISSUE #3420: Outgoing payments from other clients not displayed on refresh
I use zap-desktop and zap-android to connect my desktop and my mobile phone to my own LND node. When I pay something with zap-android or directly via LND the payment gets not displayed in zap-desktop, even after hitting Refresh activity list. The only way to really refresh is to disconnect and reconnect.

## Description

Sending an outgoing payment with another client results in zap-desktop not displaying this payment, even after hitting refresh. Incoming payments are recognized instantly (even without hitting refresh).

## Expected Behavior

At least after hitting refresh activity list outgoing payments done by other clients of the lnd node should be displayed in the list.

## Actual Behavior

The outgoing payments are not displayed after refreshing (only reconnecting helps).

## Steps to Reproduce

- 1. Connect zap-desktop to own LND-node
- 2. Send payment using lncli directly
- 3. Payment does not show up in zap-desktop, even after refreshing

## Your Environment

- Zap version: 0.6.2
- Operating System and version: arch linux

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

Fetch latest payment data if we detect an HTLC settlement event that was probably not triggered by us. 

## Motivation and Context:

Ensures that payments sent by other wallet clients show up immediately in the activity list.

fix #3420

## How Has This Been Tested?

Manually

## Types of changes:

Enhancement

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: services/grpc/grpc.js [hunk 1]
```diff
@@ -250,6 +254,12 @@ class ZapGrpc extends EventEmitter {
       // Set up the subscription.
       const { serviceName, methodName } = this.availableSubscriptions[key]
       const service = this.services[serviceName]
+
+      if (!service) {
+        grpcLog.warn(`gRPC subscription "${key}" not available.`)
```
Comment (korhaliv) [inline services/grpc/grpc.js:259]: Maybe worth logging some additional data here too just incase:
`Attempt to initialize ${serviceName} has failed. gRPC subscription "${key}"  not available.`
Since the service is accessed via `this.services[serviceName]` this would give us more debug info.

File: services/grpc/router.subscriptions.js [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+ * subscribeHtlcEvents - Call lnd grpc subscribeHtlcEvents method and emit events on updates to the stream.
+ *
+ * @param {object} payload Payload
+ * @returns {object} Grpc Call
+ */
+function subscribeHtlcEvents(payload = {}) {
+  if (this.service.subscribeHtlcEvents) {
+    const call = this.service.subscribeHtlcEvents(payload)
+    call.on('data', data => {
+      grpcLog.debug('HTLC EVENT: %o', data)
```
Comment (korhaliv) [inline services/grpc/router.subscriptions.js:15]: Consider using something like `HTLC DATA EVENT` in order to be able to more easily distinguish between various event types. Sorta like what we do in `lightning.subscriptions`

**Comment by mrfelton** [comment]
Thanks. Updated
