### PR TITLE
fix(i18n): add intl support for selects

### LINKED ISSUE #2073: Filter dropdowns should be translatable
## Detailed Description

Filter dropdowns are currently not translatable as the strings are added in the reducers. They should be made translatable.

### PR DESCRIPTION
**Pull request by korhaliv**
## Description:
Resolves #2073 

## How Has This Been Tested?
Manually

## Types of changes:
Refactor/bugfix

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [x] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: renderer/components/UI/Select.js [hunk 1]
```diff
@@ -70,40 +70,45 @@ const StyledInput = styled(BasicInput)`
...
+function useIntl(items, messageMapper, intl) {
+  return useMemo(() => {
+    // if messageMapper is not set just original items array
+    // in this case items should already contain value prop for each key
+    if (!messageMapper) {
+      return items
     }
-  }
+    return items.map(({ key }) => {
+      return { key, value: intl.formatMessage({ ...messageMapper(key) }) }
```
Comment (mrfelton) [inline renderer/components/UI/Select.js]: It might be worth adding a check here to verify that `.messageMapper(key)` returns something and if not just return the item key as the value.

File: renderer/components/UI/Select.js [hunk 2]
```diff
@@ -70,40 +70,45 @@ const StyledInput = styled(BasicInput)`
...
-    items: [],
-    iconSize: 8,
-  }
-
-  inputRef = React.createRef()
-
-  blurInput = () => {
-    if (this.inputRef.current) {
-      this.inputRef.current.blur()
+function useIntl(items, messageMapper, intl) {
```
Comment (mrfelton) [inline renderer/components/UI/Select.js]: Maybe move this to the `hooks` dir?

File: renderer/components/UI/Select.js [hunk 3]
```diff
@@ -70,40 +70,45 @@ const StyledInput = styled(BasicInput)`
...
+    })
+  }, [items, messageMapper, intl])
+}
 
-  renderSelectOptions = (highlightedIndex, selectedItem, getItemProps) => {
-    let { items, theme } = this.props
+function Select(props) {
+  const { intl, messageMapper } = props
+  const inputRef = useRef(null)
+  // eslint-disable-next-line react/destructuring-assignment
```
Comment (mrfelton) [inline renderer/components/UI/Select.js]: Can you pull `items` out of props in line 104 to avoid this?

Comment (korhaliv) [reply renderer/components/UI/Select.js]: the idea was to override items prop so later there won't be a mistake because props.items will be used

File: renderer/components/UI/Select.js (hunk 1 above)
Comment (korhaliv) [reply renderer/components/UI/Select.js]: This has pros and cons. Currently, mapper works as a "compile time" checker. so if the message is missing it will throw an error which would be easily detectable. Silently falling back to a key is ok, but may bring more problems than improvements. What do you think?
