### PR TITLE
fix(ui): retain channel view mode on logout

### LINKED ISSUE #2988: Preferred channel list view mode not retained through wallet logout
## Description

Channel list view mode not retained 

## Expected Behavior

Preferred channel list view mode should be remembered across logins

## Actual Behavior

Channel list view mode always resets to `card` view after logging into a wallet

## Steps to Reproduce

1. Log into a wallet
2. Open Manage Channels screen and set view mode to list view
3. log out of the wallet
4. Log back in and go back to the Manage Channels page

Note that it's back on the card view again.

## Context

Channes UI

### PR DESCRIPTION
**Pull request by bolatovumar**
## Motivation and Context:

fix #2988

## How Has This Been Tested?

Manually

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: renderer/reducers/channels.js [hunk 1]
```diff
@@ -843,7 +844,12 @@ const channelSortSelector = state => state.channels.sort
 const channelSortOrderSelector = state => state.channels.sortOrder
 const filterSelector = state => state.channels.filter
 const nodesSelector = state => networkSelectors.nodes(state)
-const viewModeSelector = state => state.channels.viewMode
+const viewModeSelector = createSelector(
+  settingsSelectors.currentConfig,
+  currentConfig => {
+    return get(currentConfig, 'channels.viewMode', config.channels.viewMode)
```
Comment (mrfelton) [inline renderer/reducers/channels.js]: `currentConfig` contains the default config merged with local config overrides, and with database overrides applied. So, you shouldn't need to set the default here as it's redundant.

Comment (bolatovumar) [reply renderer/reducers/channels.js]: OK, will update.

Comment (bolatovumar) [reply renderer/reducers/channels.js]: Alright, done.

File: renderer/reducers/channels.js [hunk 2]
```diff
@@ -843,7 +844,10 @@ const channelSortSelector = state => state.channels.sort
 const channelSortOrderSelector = state => state.channels.sortOrder
 const filterSelector = state => state.channels.filter
 const nodesSelector = state => networkSelectors.nodes(state)
-const viewModeSelector = state => state.channels.viewMode
```
Comment (mrfelton) [inline renderer/reducers/channels.js]: Since `state.channels.viewMode` is no longer used, I'd suggest that we remove it from the state altogether to avoid confusion.

Comment (bolatovumar) [reply renderer/reducers/channels.js]: @mrfelton I hope I understood your correctly. See the follow-up commit.

Comment (mrfelton) [reply renderer/reducers/channels.js]: Yes, that's right @bolatovumar . However, the seconds commit should have the scope `refactor` instead of `fix` since it does not fix an actual user facing bug and therefore is not something that we'd want to include in the changelog.

**Comment by mrfelton** [comment]
Also note tests seem to be failing @bolatovumar . Probably need to update the test snapshots since you have modified the state.

**Comment by bolatovumar** [comment]
@mrfelton ok, updated test snap files and squashed the commits into one
