### PR TITLE
fix(onboarding): retain wallet addresses in state

### LINKED ISSUE #3182: Deposit address only shows for a split second when syncing new local wallet
## Description

Deposit address only shows for a split second when syncing new local wallet

## Expected Behavior

Deposit address should show for the full sync process

## Actual Behavior

Only shows for a split second at the start of the sync

## Steps to Reproduce

Create a new local wallet

## Context

Onboarding

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

Ensure that newly generated wallet addresses are retained in state and available to the ui after generation.

## Motivation and Context:

Fix #3182

## How Has This Been Tested?

Manually

## Types of changes:

Fix

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: renderer/reducers/address.js [hunk 1]
```diff
@@ -67,15 +67,23 @@ export const initAddresses = () => async (dispatch, getState) => {
...
-      })
-    )
-    dispatch({ type: FETCH_ADDRESSES_SUCCESS, addresses })
+    const fetchAddresses = async types => {
+      const data = {}
+      await Promise.all(
+        types.map(async type => {
+          if (addresses[type]) {
+            data[type] = addresses[type]
+            return
```
Comment (korhaliv) [inline renderer/reducers/address.js]: maybe just add else? probably no sense in using `return` in map

Comment (mrfelton) [reply renderer/reducers/address.js]: updated
