### PR TITLE
Ensure correct expire date for invoices with far future expiry

### LINKED ISSUE #3144: Invoice with expiry in far future shows as expired on invoice detail page
## Description

Invoice with expiry in far future shows as expired on invoice detail page

## Expected Behavior

Should show actual expiry date.

## Actual Behavior

Shows as expired

## Possible Fix

This is because we use the `Countdown` component to display the expiry date which uses `setInterval` which can not handle large numbers.

Consider not using the Countdown component if the date is in the far future.

## Steps to Reproduce

Create invoice with expiry in 1 year and view the invoice detail page

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

The largest number (ms) supported by setInterval is 2147483647. If countdown expire date is outside of this range do not use a timer.

Note: Technically if a user was to keep a countdown on the screen for over 24 days it would display an inaccurate expired message, but in practice this is probably such an edge case that it's not worth investing time into addressing at this point.

## Motivation and Context:

Fix #3144

## How Has This Been Tested?

Manually

## Types of changes:

Fix

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [x] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: renderer/components/UI/Countdown.js [hunk 1]
```diff
@@ -39,15 +40,17 @@ class Countdown extends React.Component {
       this.expiresIn = expiresIn
     }
 
-    if (expiresIn >= 0) {
+    // The largest number (ms) supported by setInterval is 2147483647.
+    // If countdown expire date is within this range setup a timer that updates isExpired state on expiry.
+    if (inRange(this.expiresIn, 0, 2147483)) {
```
Comment (korhaliv) [inline renderer/components/UI/Countdown.js]: And if it's not in range (>~25 days?) That's a rare case, but if expiry is out of range we could setup a timer that will check in 2147483 secs again and if it's again out of range setup the timer again and so on, until expiry is in range. This probably has a very limited real world application, but would bug free. What do you think?

Comment (mrfelton) [reply renderer/components/UI/Countdown.js]: I've done a refactor of this component to convert it to a functional component, simplify it somewhat, and use the `useTimeout` hook to handle updating the isExpired state.

This has resolved the visible bugs that were present and that I was seeking to fix in this PR. Technically, the `useTimeout` hook itself doesn't properly support far future timeouts but in reality this is an edge case, not something that really affects us, and not something that I want to address here.

I've created a separate issue to enhance the `useTimeout` hook to support far future expiry dates. See https://github.com/LN-Zap/zap-desktop/issues/3159
