### PR TITLE
Fix number of issues in pay form

### LINKED ISSUE #3175: Redundant fee fetch when paying LN invoice
## Description
App fetches fees when user tries to pay LN invoice which is redundant

### LINKED ISSUE #3176: Next button is disabled for a valid bitcoin address
## Description
image
Next button is disabled for a valid bitcoin address
Steps to repro:
1. Press Pay
2. Paste valid bitcoin address
3. Hit back

### PR DESCRIPTION
**Pull request by korhaliv**
## Description:
Fix number of issues in Pay form:
- resolves #3175 
- resolves #3176 
- Adds trimming to pay form address/PR input

## How Has This Been Tested?
Manually

## Types of changes:
Bugfixes/Minor perf improvements

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [ ] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: renderer/components/Pay/PayPanelFooter.js [hunk 1]
```diff
@@ -100,14 +98,13 @@ const PayPanelFooter = props => {
...
   const hasBackButton = currentStep !== PAY_FORM_STEPS.address
-  const hasSubmitButton = currentStep !== PAY_FORM_STEPS.address || (isOnchain || isLn)
 
   return (
     <Flex flexDirection="column">
       {renderLiquidityWarning(props)}
       <PayButtons
         hasBackButton={hasBackButton}
-        hasSubmitButton={hasSubmitButton}
+        hasSubmitButton
```
Comment (mrfelton) [inline renderer/components/Pay/PayPanelFooter.js]: This seems wrong. The next button is never supposed to be visible on the first step of the pay form since the form automatically moves you to the next step after entering a valid address.

Comment (korhaliv) [reply renderer/components/Pay/PayPanelFooter.js]: what if you press back?

Comment (mrfelton) [reply renderer/components/Pay/PayPanelFooter.js]: Ok, so perhaps we should make it visible only after going back?

Right now you have to edit the value for it to pick up the change and move you forwards

Comment (korhaliv) [reply renderer/components/Pay/PayPanelFooter.js]: Not sure i understand. If you don't hit back then you can't see  it because you can't see that  form

Comment (mrfelton) [reply renderer/components/Pay/PayPanelFooter.js]: When the form first loads, the button should not be visible because the form is empty. Then you enter an address and it automatically moves you forwards to the next step. If you go back then the button could show in order to address the issue you are observing with the button not being visible when you go back.

Comment (korhaliv) [reply renderer/components/Pay/PayPanelFooter.js]: I see makes sense. Still maybe this is not actually desired. To my knowledge this is the only place where we would hide the button. In all other places we usually allow user to do one attempt and then do inline validation. I understand that here we have some sort of automatic transition, but i'm not sure this is enough to justify hiding of the button. What do u think

Comment (mrfelton) [reply renderer/components/Pay/PayPanelFooter.js]: That's true. I think that the thought process here was that there would be no possible reason for anyone to do anything on this form other than to paste an address, so why clutter the ui with distractions? Instead, lets make the page as basic and single-purpose as possible. Not that a submit button is probably too much of a distraction, but that was the logic.

I think the best thing would be to keep it hidden if the user is new to the form in order to keep the existing behaviou as designed, and show it if the user is coming back from another form step
