### PR TITLE
fix(ui): incorrect open btn placement in OpenDialogInput errorneus state

### LINKED ISSUE #2987: UI Bug - Channel backups error state
When getting an error setting the local location of my channel backup, the UI broke a little bit:

Screen Shot 2019-10-14 at 9 37 42 AM

### PR DESCRIPTION
**Pull request by korhaliv**
## Description:
fix #2987

## How Has This Been Tested?
Manually

## Screenshots (if appropriate):
image

## Types of changes:
Layout bugfix

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [ ] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: renderer/components/Form/OpenDialogInput.js [hunk 1]
```diff
@@ -19,14 +19,15 @@ const InnerInput = styled(BasicInput)`
...
 const OpenDialogInput = props => {
-  const { mode, ...rest } = props
+  const { mode, label, ...rest } = props
   const [spaceProps, otherProps] = extractSpaceProps(rest)
   return (
     <WithOpenDialog
       render={({ openDialog }) => (
-        <Flex alignItems="center" {...spaceProps}>
-          <InnerInput width={1} {...otherProps} />
+        <Flex alignItems="flex" {...spaceProps}>
```
Comment (mrfelton) [inline renderer/components/Form/OpenDialogInput.js]: Is `flex` a valid option for `alignItems`?

Comment (korhaliv) [reply renderer/components/Form/OpenDialogInput.js]: lol, good catch. that should go completely
