### PR TITLE
fix(forms): more robust handling for amount inputs

### LINKED ISSUE #1547: Pay form goes blank when entering period in input
When trying to make an on-chain payment, if you enter a `.`, with the purpose of sending an amount less than `1`, like `.5` Zap goes blank.

Expected behavior is you are allowed to type `.5` into the payform input

### PR DESCRIPTION
**Pull request by mrfelton**
## Description:

- Improve input mask masking for crypto/fiat amount input fields when a period character is entered
- Extract duplicate code from `FiatAmountInput` and `CryptoAmountInput` components into a reusable HOC.

## Motivation and Context:

Fix #1547 in which entering `.` into the crypto amount input would cause the app to crash.

## How Has This Been Tested?

Manually

## Types of changes:
Bug fix

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have reviewed and updated the documentation accordingly.
- [x] I have read the _CONTRIBUTING_ document.
- [ ] I have added tests to cover my changes where needed.
- [ ] All new and existing tests passed.
- [x] My commits have been squashed into a concise set of changes.

### CODE REVIEW

File: app/components/UI/CryptoAmountInput.js [hunk 1]
```diff
@@ -152,4 +124,4 @@ class WrappedCryptoAmountInputAsField extends React.Component {
   }
 }
 
-export default WrappedCryptoAmountInputAsField
+export default asField(withNumberInputMask(WrappedCryptoAmountInputAsField))
```
Comment (korhaliv) [inline app/components/UI/CryptoAmountInput.js]: Could haved used `compose` from `redux`, but that's just a matter of preference really
